#!/usr/bin/env node
// Assemble the deployable site into dist/.
//
// The app is static files, so "building" is mostly copying - but not copying
// the whole folder. Serving frontend/ directly would publish node_modules
// (tens of megabytes of build tooling, fetchable by anyone), package.json, and
// the Tailwind *source* alongside the compiled stylesheet. This lists what a
// browser actually needs, so the deployed artifact is exactly that.
//
// Run after build:config and build:css, which generate the two files here that
// are not committed.

import { cpSync, mkdirSync, rmSync, existsSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const DIST = join(HERE, 'dist');

// Everything the page loads, and nothing else. Ordered as index.html needs it.
const INCLUDE = [
  'index.html',
  'assets',
  'src/config.js',       // generated by build-config.mjs
  'src/app.build.css',   // generated by build:css
  'src/styles.css',
  'src/bridge.js',
  'src/catalog.js',
  'src/app.js',
  'src/segment-player.js',
  'src/neutv-api.js',
];

rmSync(DIST, { recursive: true, force: true });
mkdirSync(join(DIST, 'src'), { recursive: true });

let bytes = 0;
const missing = [];
for (const rel of INCLUDE) {
  const from = join(HERE, rel);
  if (!existsSync(from)) { missing.push(rel); continue; }
  cpSync(from, join(DIST, rel), { recursive: true });
  bytes += statSync(from).isDirectory() ? 0 : statSync(from).size;
}

if (missing.length) {
  // A missing file here is a page that half-loads in production and works
  // locally, which is the worst way to find out.
  console.error(`\n  Missing from the build: ${missing.join(', ')}\n`);
  process.exit(1);
}

console.log(`  dist/ assembled: ${INCLUDE.length} entries, ${(bytes / 1024).toFixed(0)}KB of files`);
