#!/usr/bin/env node
// Writes src/config.js, which tells the page where the API lives.
//
// The app has no bundler and no environment at runtime - it is static files in
// a browser - so the one thing that differs between deployments has to be baked
// in at build time. Served by the gateway itself, the API is same-origin and
// this file is empty. Served from Vercel with the gateway on its own host, it
// carries that host.
//
//   NEUTV_API_BASE=https://api.neu.tv node build-config.mjs
//
// Generated, so it is gitignored: a committed copy would be one deployment's
// URL shipped to every other deployment.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, 'src', 'config.js');

// Trailing slash trimmed: the client appends "/api/v1", and "//api/v1" is a
// different path to every router that has ever existed.
const base = (process.env.NEUTV_API_BASE || '').trim().replace(/\/+$/, '');

if (base && !/^https?:\/\//.test(base)) {
  console.error(`\n  NEUTV_API_BASE must be an absolute http(s) URL, got "${base}"\n`);
  process.exit(1);
}

writeFileSync(OUT, base
  ? `// Generated by build-config.mjs. Do not edit.\nwindow.NEUTV_API_BASE = ${JSON.stringify(base)};\n`
  : '// Generated by build-config.mjs. No NEUTV_API_BASE set, so the API is same-origin.\n');

console.log(`  API base: ${base || '(same origin)'}`);
